apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenks-pv-volume
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
#    path: "/mnt/data"
    path: "/mnt/vda1/jenkins"
