apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
#  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins

#apiVersion: v1
#kind: Service
#metadata:
#  name: jenkins
#  namespace: jenkins
#spec:
#  selector:
#    app: jenkins
#  ports:
#    - name: http
#      protocol: TCP
#      port: 8080
#      targetPort: 8080
#  externalIPs:
#    - 192.168.39.36

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: jenkins
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-sshd
  namespace: jenkins
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: jenkins
