#apiVersion: v1
#kind: Service
#metadata:
#  name: jenkins
#  namespace: jenkins
#spec:
#  type: NodePort
#  type: LoadBalancer
#  ports:
#    - port: 8080
#      targetPort: 8080
#      nodePort: 30000
#  selector:
#    app: jenkins

apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  externalIPs:
    - 192.168.39.36
