apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler
  namespace: jenkins
spec:
  restartPolicy: Never
  volumes:
  - name: jenks-pv-storage 
    hostPath:
      path: "/mnt/vda1/jenkins"
  containers:
  - name: pv-recycler
    image: "k8s.gcr.io/busybox"
    command: ["/bin/sh", "-c", "test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z \"$(ls -A /scrub)\" || exit 1"]
    volumeMounts:
    - name: jenks-pv-storage
      mountPath: "/var/jenkins_home"
